# Generated by Django 4.0.1 on 2023-01-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisdb',
            old_name='published_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='thesisdb',
            old_name='published_year',
            new_name='year',
        ),
    ]
