# Generated by Django 4.0.1 on 2022-12-15 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisdb',
            name='image_banner',
        ),
    ]
