# Generated by Django 4.0.1 on 2022-12-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_remove_thesisdb_image_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='image_banner',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
