# Generated by Django 4.0.1 on 2023-01-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0002_rename_published_month_thesisdb_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisdb',
            old_name='month',
            new_name='published_month',
        ),
        migrations.RenameField(
            model_name='thesisdb',
            old_name='year',
            new_name='published_year',
        ),
    ]
