# Generated by Django 4.0.1 on 2023-01-06 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_rename_month_thesisdb_published_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisdb',
            name='published_month',
        ),
        migrations.RemoveField(
            model_name='thesisdb',
            name='published_year',
        ),
    ]
