# Generated by Django 4.0.1 on 2022-12-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0003_thesisdb_image_banner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coldept',
            old_name='department_head',
            new_name='department_abbreviation',
        ),
        migrations.AlterField(
            model_name='requestpdf',
            name='request_status',
            field=models.CharField(choices=[('Approve', 'Approve')], default='Pending', max_length=10),
        ),
    ]
