# Generated by Django 4.0.1 on 2023-01-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_thesisdb_published_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='published_month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=15),
        ),
    ]
