# Generated by Django 3.2.3 on 2022-12-18 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0004_alter_requestpdf_request_status'),
        ('libraryApp', '0005_remove_thesisdb_image_banner'),
    ]

    operations = [
    ]
