# Generated by Django 4.0.1 on 2022-12-18 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0005_remove_thesisdb_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('A', 'Invalid Format')]),
        ),
    ]
