# Generated by Django 4.0.1 on 2023-01-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_thesisdb_published_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='published_month',
            field=models.CharField(choices=[('1', 'January'), ('2', 'February'), ('3', 'March'), ('4', 'April'), ('5', 'May'), ('6', 'June'), ('7', 'July'), ('8', 'August'), ('9', 'September'), ('10', 'October'), ('11', 'November'), ('12', 'December')], default='1', max_length=15),
        ),
    ]
