# Generated by Django 3.2.3 on 2022-12-18 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0006_merge_20221218_1038'),
        ('libraryApp', '0007_alter_thesisdb_author'),
    ]

    operations = [
    ]
