# Generated by Django 4.0.1 on 2023-01-07 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0007_alter_thesisdb_published_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisdb',
            name='published_date',
        ),
    ]
