# Generated by Django 4.0.1 on 2022-12-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_alter_thesisdb_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpdf',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approve')], default='Pending', max_length=10),
        ),
    ]
