# Generated by Django 4.0.1 on 2023-01-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0008_remove_thesisdb_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='previous_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
