# Generated by Django 4.0.1 on 2023-01-09 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_thesisdb_previous_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='abstract',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must be at least 50 characters')]),
        ),
    ]
