# Generated by Django 3.2.3 on 2022-12-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0009_alter_thesisdb_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpdf',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approve')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='thesisdb',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='thesisdb',
            name='published_status',
            field=models.CharField(choices=[('Approved', 'Approve'), ('Rejected', 'Reject')], default='Pending', max_length=10),
        ),
    ]
