# Generated by Django 4.0.1 on 2023-01-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0010_alter_thesisdb_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requestpdf',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thesisdb',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coldept',
            name='department_abbreviation',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
