# Generated by Django 4.0.1 on 2022-12-18 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0010_alter_thesisdb_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]\\w+,\\s*[A-Z]\\.(?:\\s+and (?:[A-Z]\\w+,\\s*[A-Z]\\.|et\\.\\s+al\\.))?\\gm', 'Invalid Format')]),
        ),
    ]
