# Generated by Django 4.0.1 on 2023-01-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0013_remove_registrations_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
