# Generated by Django 4.0.1 on 2023-01-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0014_thesisdb_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisdb',
            name='is_read',
        ),
    ]
