# Generated by Django 4.0.1 on 2022-12-19 04:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0015_alter_thesisdb_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=2, null=True, validators=[django.core.validators.RegexValidator('[A-Z]+.', 'Initial must contain period')])),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.thesisdb')),
            ],
        ),
    ]
