# Generated by Django 4.0.1 on 2022-12-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0016_alter_thesisdb_author_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
