# Generated by Django 4.0.1 on 2022-12-21 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0017_delete_authors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=2, null=True)),
                ('thesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryApp.thesisdb')),
            ],
        ),
    ]
