# Generated by Django 4.0.1 on 2022-12-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0019_alter_authors_middle_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='adviser',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thesisdb',
            name='apa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thesisdb',
            name='mla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
