# Generated by Django 4.0.1 on 2022-12-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0020_thesisdb_adviser_thesisdb_apa_thesisdb_mla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisdb',
            old_name='apa',
            new_name='apa_citation',
        ),
        migrations.RenameField(
            model_name='thesisdb',
            old_name='mla',
            new_name='mla_citation',
        ),
    ]
