# Generated by Django 4.0.1 on 2022-12-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0022_remove_thesisdb_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='author',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
