# Generated by Django 4.0.1 on 2022-12-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0025_thesisdb_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thesisdb',
            old_name='apa_citation',
            new_name='apa',
        ),
        migrations.RenameField(
            model_name='thesisdb',
            old_name='mla_citation',
            new_name='chicago',
        ),
        migrations.AddField(
            model_name='thesisdb',
            name='mla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
