# Generated by Django 4.0.1 on 2022-12-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0026_rename_apa_citation_thesisdb_apa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='published_date',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
