# Generated by Django 3.2.3 on 2022-12-25 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0010_auto_20221218_1435'),
        ('libraryApp', '0026_rename_apa_citation_thesisdb_apa_and_more'),
    ]

    operations = [
    ]
