# Generated by Django 4.0.1 on 2022-12-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0027_alter_thesisdb_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesisdb',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
