# Generated by Django 4.0.1 on 2022-12-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0028_alter_thesisdb_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesisdb',
            name='apa',
        ),
        migrations.RemoveField(
            model_name='thesisdb',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thesisdb',
            name='chicago',
        ),
        migrations.RemoveField(
            model_name='thesisdb',
            name='mla',
        ),
    ]
