# Generated by Django 3.2.3 on 2022-12-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0027_merge_20221225_1240'),
        ('libraryApp', '0029_remove_thesisdb_apa_remove_thesisdb_author_and_more'),
    ]

    operations = [
    ]
