# Generated by Django 4.0.1 on 2022-12-29 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0029_remove_thesisdb_apa_remove_thesisdb_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesisinfo', to='libraryApp.thesisdb'),
        ),
    ]
