# Generated by Django 4.0.1 on 2022-12-29 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0030_alter_authors_thesis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='libraryApp.thesisdb'),
        ),
    ]
