# Generated by Django 4.0.1 on 2022-12-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0031_alter_authors_thesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesisdb',
            name='apa',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
