# Generated by Django 3.2.3 on 2022-12-30 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0031_auto_20221229_1935'),
        ('libraryApp', '0034_thesisdb_chicago'),
    ]

    operations = [
    ]
