# Generated by Django 3.2.3 on 2022-12-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0035_merge_0031_auto_20221229_1935_0034_thesisdb_chicago'),
        ('libraryApp', '0035_rename_date_approve_requestpdf_date_evaluated'),
    ]

    operations = [
    ]
