# Generated by Django 4.0.1 on 2022-12-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0035_rename_date_approve_requestpdf_date_evaluated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='middle_initial',
        ),
        migrations.AlterField(
            model_name='requestpdf',
            name='request_status',
            field=models.CharField(choices=[('Approved', 'Approve'), ('Declined', 'Decline')], default='Pending', max_length=10),
        ),
    ]
