# Generated by Django 3.2.3 on 2022-12-31 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0036_merge_20221231_1246'),
        ('libraryApp', '0036_remove_authors_middle_initial_and_more'),
    ]

    operations = [
    ]
