# Generated by Django 4.0.1 on 2023-01-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0036_remove_authors_middle_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
