# Generated by Django 3.2.3 on 2023-01-01 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0037_merge_20221231_1544'),
        ('libraryApp', '0037_registrations_is_admin'),
    ]

    operations = [
    ]
