# Generated by Django 4.0.1 on 2023-01-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0037_registrations_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrations',
            name='submission_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
