# Generated by Django 3.2.3 on 2023-01-02 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0038_merge_20230101_1549'),
        ('libraryApp', '0038_registrations_submission_agreement'),
    ]

    operations = [
    ]
