# Generated by Django 4.0.1 on 2023-01-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0038_registrations_submission_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrations',
            name='submission_agreement',
        ),
        migrations.AddField(
            model_name='thesisdb',
            name='submission_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
