# Generated by Django 3.2.3 on 2023-01-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryApp', '0039_merge_20230102_2142'),
        ('libraryApp', '0039_remove_registrations_submission_agreement_and_more'),
    ]

    operations = [
    ]
